name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Get commit hash
        id: sha
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build images and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/thibaultnocchi/collechandler:latest
            ghcr.io/thibaultnocchi/collechandler:${{ steps.sha.outputs.sha }}
